wrycu/arma_server_manager

- backend/.env.example
- backend/app/__init__.py
- backend/app/config.py
- backend/app/models/mod.py
- backend/app/models/mod_image.py
- backend/app/routes/api.py
- backend/app/routes/arma3.py
- backend/app/utils/helpers.py
- backend/pyproject.toml
- backend/uv.lock
* add basic functionality to add/remove/edit mod subscriptions
* does not actually trigger downloads, though the functionality is present
* minor updates to DB - if it was already created, it'll need to be dropped
> feat(backend): mod subs

- backend/.env.example
- backend/app/config.py
- backend/app/models/mod.py
- backend/app/routes/arma3.py
- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* initial support for async jobs
* download / delete a subscribed mod
> feat(backend): add async support

- .husky/pre-commit
- frontend/src/components/layout/AppSidebar.tsx
- frontend/src/components/layout/MainContent.tsx
- frontend/src/features/server/components/CompactServerStatus.tsx
- frontend/src/features/server/components/ServerCharts.tsx
- frontend/src/features/server/index.tsx
- frontend/src/features/settings/components/NotificationSettings.tsx
- frontend/src/features/settings/components/SecuritySettings.tsx
- frontend/src/features/settings/components/ServerSettings.tsx
- frontend/src/features/settings/components/index.ts
- frontend/src/features/settings/index.tsx
- frontend/src/features/settings/types.ts
- Adds a settings page to the UI
> feat: added a settings page

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/ui/drawer.tsx
- frontend/src/features/server/components/TerminalConsole.tsx
- frontend/src/features/server/index.tsx
- Adds a little terminal window that pops out for the server console
> feat: added server console terminal

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/common/PageTitle.test.tsx
- frontend/src/lib/breadcrumbs.test.ts
- frontend/src/lib/breadcrumbs.ts
- frontend/test/setup.ts
- frontend/tsconfig.app.json
- frontend/vite.config.ts
- adds vitest for frontend components
> set up Vitest + RTL; add breadcrumbs and PageTitle tests

- backend/app/models/collection.py
- backend/app/models/mod_collection_entry.py
- backend/app/routes/arma3.py
- backend/app/utils/helpers.py
- backend/tests/test_api.py
* support for collections
* note that this comes with DB schema changes
> feat(backend): collections

- backend/app/models/notification.py
- backend/app/routes/arma3.py
- backend/app/tasks/background.py
- backend/app/utils/helpers.py
- backend/tests/test_api.py
* implement webhook notifications
> feat(backend): notifications

- frontend/src/components/AddModsDialog.tsx
- frontend/src/components/CollectionsModsList.tsx
- frontend/src/components/ModsColumns.tsx
- frontend/src/components/ModsDataRowActions.tsx
- frontend/src/components/ModsDataTable.tsx
- frontend/src/hooks/useCollections.ts
- frontend/src/hooks/useMods.ts
- frontend/src/lib/db-config.ts
- frontend/src/providers/db-provider.tsx
- frontend/src/types/api.ts
- frontend/src/types/collections.ts
- frontend/src/types/mods.ts
- use actual mod subscriptions api instead of mock data
- update mods types in frontend to better match the api
> feat: switch the frontend from mock data to real mods subscriptions api

- backend/app/tasks/background.py
- backend/app/utils/helpers.py
- backend/pyproject.toml
- backend/uv.lock
* checks if the server is running and cancels mod updates if it is
> feat(backend): mod updates

- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* swap stopping server to OS-agnostic function
* also, don't subprocess :)
> refactor(backend): server stop

- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* check for, and sanitize, path traversal in mod filename data
> fix(backend): path traversal

- backend/app/models/collection.py
- backend/app/models/server_config.py
- backend/app/routes/arma3.py
- backend/app/tasks/background.py
- backend/app/utils/helpers.py
- backend/tests/test_api.py
Remove client_mods and server_mods from server config; derive them from the collection ID when starting/stopping.
> Server config

- backend/app/routes/arma3.py
- backend/app/utils/helpers.py
* adds an API endpoint to retrieve contents of steam collection
> feat(steam): get collection details

- backend/.env.example
- backend/app/routes/arma3.py
* improve example celery config to use sqlite for results
* update job status endpoint to return an object if the task being queried ran without returning anything
> refactor(celery): defaults

- backend/app/tasks/background.py
* better handle config values not being set (resulting in a None object being passed to a command...)
> fix(backend): server

- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* makes server start actually work (at least via the API call)
* improves error handling with async tasks overall
> Server start

- backend/app/models/collection.py
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/CollectionsModsList.tsx
- frontend/src/hooks/useCollections.ts
- frontend/src/pages/CollectionDetailPage.tsx
- frontend/src/services/collections.service.ts
- adds drag and drop mod re-ordering for mod list
- changes backend api to return the mods in a collection in their load order
> Implement drag-and-drop reordering for mod load order in collections

- backend/README.md
- backend/app/routes/arma3.py
- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* add the ability to trigger downloads for all or individual mods (check readme)
* slightly improve docstrings for a few functions
> feat(backend): mods

- backend/app/utils/helpers.py
* validate steamCMD exists during startup
> feat(backend): steamcmd

- frontend/src/components/ModDetailSidebar.tsx
- frontend/src/components/ScheduleDetailSidebar.tsx
- frontend/src/components/ui/right-sidebar.tsx
- Updated header styles, enhanced delete confirmation dialogs, and adjusted layout for metadata grids.
- Removed unused imports and optimized button sizes for better accessibility. 
- Updated RightSidebarFooter for consistent padding and styling.
> Improve detail sidebar visual hierarchy

- backend/app/models/server_config.py
- backend/app/tasks/background.py
- backend/app/utils/helpers.py
* update server running state when starting/stopping
> feat(backend): server running

- frontend/src/hooks/useMods.test.ts
- frontend/src/hooks/useMods.ts
> Removed mod download success toast on API response.

- frontend/src/components/ModsColumns.tsx
- frontend/src/components/ModsDataTable.tsx
- frontend/src/components/ModsSubscribeDialog.tsx
- frontend/src/pages/ModsPage.tsx
- frontend/src/services/mods.service.ts
- frontend/src/types/api.ts
- frontend/src/types/index.ts
- subscribe to mod collections from steam workshop
- batch delete mods (for when u subscribe to way too many)
> Add support for subscribing to collections

- backend/app/routes/arma3.py
- backend/app/utils/helpers.py
* add `include_sensitive` flag to /servers endpoint. Previously, it was only supported in the specific server endpoint
> fix(backend): servers

- backend/.env.example
* change the .env.example to be prod
> chore(env): default to production

- frontend/src/components/ServerSettings.tsx
- frontend/src/hooks/useServer.ts
- frontend/src/pages/SettingsPage.tsx
- frontend/src/services/server.service.ts
- Show server and admin password on settings page
- Improve compactness of settings page form layout
> Show server and admin password on settings page

- frontend/src/components/ModsSubscribeDialog.tsx
- frontend/src/services/mods.service.ts
- exclude already sub'd mods from collection subscription
- notify when all mods from that collection were already subscribed
> Add support for excluding already subscribed mods from new collection subscription

- frontend/src/components/ModsSubscribeDialog.tsx
- frontend/src/pages/ModsPage.tsx
- allow user to download mod immediately upon subscription
> Update ModsSubscribeDialog to include 'Download now' option

- frontend/src/hooks/useCollections.ts
- frontend/src/services/collections.service.ts
- frontend/src/types/api.ts
- Fixes ability to delete a mod from a collection
> Fix remove mod from collection service
